### ISSUE TITLE
Pre-commit error during initialization

### ISSUE THREAD

**Issue by CptQuak** [Nospoko/midi-internship#5]
Hi, I have tried to run the pre-commit hook, but encountered the following issue.

```
fatal: repository 'https://gitlab.com/pycqa/flake8.git/' not found
```

Found one related SO post, it looks like that they have moved repo to GitHub, so it will always fail.
https://stackoverflow.com/questions/74843772/pre-commit-suddenly-fails-to-install-flake8

Do you plan to update it in our repo?

---
Full logs:
### version information

```
pre-commit version: 3.3.3
git --version: git version 2.34.1
sys.version:
    3.9.17 (main, Jul  5 2023, 20:41:20) 
    [GCC 11.2.0]
sys.executable: /home/quak/miniconda3/envs/midi/bin/python
os.name: posix
sys.platform: linux
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
stdout: (none)
stderr:
    warning: git-credential-manager-core was renamed to git-credential-manager
    warning: see https://aka.ms/gcm/rename for more information
    remote: The project you were looking for could not be found or you don't have permission to view it.
    fatal: repository 'https://gitlab.com/pycqa/flake8.git/' not found
```

```
Traceback (most recent call last):
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/store.py", line 202, in clone_strategy
    self._shallow_clone(ref, _git_cmd)
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/store.py", line 184, in _shallow_clone
    git_cmd('-c', git_config, 'fetch', 'origin', ref, '--depth=1')
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/store.py", line 199, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', '-c', 'protocol.version=2', 'fetch', 'origin', '3.9.2', '--depth=1')
return code: 128
stdout: (none)
stderr:
    warning: git-credential-manager-core was renamed to git-credential-manager
    warning: see https://aka.ms/gcm/rename for more information
    remote: The project you were looking for could not be found or you don't have permission to view it.
    fatal: repository 'https://gitlab.com/pycqa/flake8.git/' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/main.py", line 414, in main
    return run(args.config, store, args)
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/commands/run.py", line 425, in run
    for hook in all_hooks(config, store)
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/repository.py", line 252, in all_hooks
    return tuple(
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/repository.py", line 255, in <genexpr>
    for hook in _repository_hooks(repo, store, root_config)
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/repository.py", line 230, in _repository_hooks
    return _cloned_repository_hooks(repo_config, store, root_config)
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/repository.py", line 196, in _cloned_repository_hooks
    manifest_path = os.path.join(store.clone(repo, rev), C.MANIFEST_FILE)
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/store.py", line 206, in clone
    return self._new_repo(repo, ref, deps, clone_strategy)
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/store.py", line 163, in _new_repo
    make_strategy(directory)
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/store.py", line 204, in clone_strategy
    self._complete_clone(ref, _git_cmd)
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/store.py", line 176, in _complete_clone
    git_cmd('fetch', 'origin', '--tags')
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/store.py", line 199, in _git_cmd
    cmd_output_b('git', *args, cwd=directory, env=env)
  File "/home/quak/miniconda3/envs/midi/lib/python3.9/site-packages/pre_commit/util.py", line 110, in cmd_output_b
    raise CalledProcessError(returncode, cmd, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
stdout: (none)
stderr:
    warning: git-credential-manager-core was renamed to git-credential-manager
    warning: see https://aka.ms/gcm/rename for more information
    remote: The project you were looking for could not be found or you don't have permission to view it.
    fatal: repository 'https://gitlab.com/pycqa/flake8.git/' not found
```

**Comment by roszcz** [comment]
@CptQuak apologies for the inconvenience! 

Does it work for you if you change the flake repo address like in the SO answer? If yes, you can use the update version for your development, if it still doesn't work feel free to not use pre-commit-hooks. You can still use flake and black.

I'll investigate the error you reported and will try to update the repo

**Comment by CptQuak** [comment]
Yeah, so I tried changing the following things:
- python: python3.9.17
- repo: https://github.com/pycqa/flake8.git

But it still failed to run, so I was searching further and from this SO https://stackoverflow.com/questions/75269700/pre-commit-fails-to-install-isort-5-11-4-with-error-runtimeerror-the-poetry-co I run the:

```
pre-commit autoupdate
```

After running auto update everything is working. I think we can close this issue.
